services:
  - type: web
    name: studybuddi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        fromDatabase:
          name: studybuddi-mysql
          property: host
      - key: DB_USER
        fromDatabase:
          name: studybuddi-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: studybuddi-mysql
          property: password
      - key: DB_NAME
        value: studybuddi
      - key: VITE_USE_HTTPS
        value: "false"
      - key: VITE_API_URL
        value: https://studybuddi.onrender.com/api

databases:
  - name: studybuddi-mysql
    databaseName: studybuddi
    user: studybuddi_user
